platform :ios, '12.0'


#target 'Example for JackPodView', do
#  use_frameworks!
#  pod 'JackPodView'
#end

target 'JackPodView_Example' do
  pod 'JackPodView', '= 0.2.0'

  target 'JackPodView_Tests' do
    pod 'JackPodView', '= 0.2.0'
    
  end
end
